# Generated by Django 4.0.3 on 2022-12-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('url', models.SlugField(max_length=260, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='anime_posters/anime_posters', verbose_name='Постер')),
                ('pubdate', models.DateField(verbose_name='Дата выхода')),
                ('episodes', models.IntegerField(default=0, verbose_name='Эпизодов')),
                ('url', models.SlugField(max_length=260, unique=True)),
                ('main_picture', models.ImageField(default='', upload_to='anime_posters/main_pictures/', verbose_name='Картинка')),
                ('video_url', models.TextField(default='', verbose_name='Ссылка на аниме')),
                ('genre', models.ManyToManyField(to='main_site.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
    ]
